[tool.isort]
src_paths = ["."]
line_length = 79
skip = ["migrations"]


line_length = 79
force_single_line = true

[tool.black]
force-exclude = '/(migrations)/'
line-length = 79
preview = true



[tool.pyright]
typeCheckingMode = "strict"
venv = "venv"
include = ["chess_manager", "core"]
exclude = ["**/venv", "**/migrations"]
reportMissingImports = true
reportGeneralTypeIssues = true
useLibraryCodeForTypes = true