[tool.isort]
src_paths = ["."]

line_length = 79
force_single_line = true

[tool.black]
line-length = 79
preview = true
extend-exclude = "migrations"


[tool.pyright]
typeCheckingMode = "strict"
include = ["chess_manager", "core"]
exclude = ["**/migrations/**", "**/__pycache__/**"]
reportMissingImports = true
reportGeneralTypeIssues = true
useLibraryCodeForTypes = true