# Generated by Django 5.1.5 on 2025-01-29 11:06

import core.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="image",
            field=models.ImageField(
                upload_to="report/",
                validators=[core.validator.validate_file_size],
            ),
        ),
    ]
