# Generated by Django 5.1.5 on 2025-01-30 08:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigIntegerField(
                default=None, primary_key=True, serialize=False
            ),
        ),
    ]
